module.exports.abide = {
  region: {
    required: true,
    pattern: 'alpha_numericLen',
    message: 'You must select a region.'
  },
  club:   {
    required: true,
    message: 'You must select a club.'
  },
  input: {
    required: true,
    minLen: 1,
    maxLen: 35
  },
  sex: {
    required: true
  }
  /**
   * Abide <=5.2.2 cannot check that 1+ checkboxes of a group is selected.
   * The checkbox group animal has to checked on the server.
   */
};

module.exports.parsley = {};

module.exports.joi = {

  // See https://github.com/spumko/joi
  schema: function (Joi) {
    return {
      region: Joi.string().required(),
      club: Joi.array().min(1),
      input: Joi.string().min(2),
      sex: Joi.string().required(),
      animal: Joi.array().min(1)
    };
  },

  // These messages override those generated by Joi.
  // A period is automatically added to the end of the msg.
  overrideMsgs: {
    //region: 'Pick a region',
    club: 'Pick 1 or more clubs',
    //input: 'Enter at least 2 chars in Text Field, even though the frontend validation permits 1',
    //sex: 'Choose a sex',
    animal: 'Choose at least 1 animal'
  }
};